# Generated by Django 2.0.6 on 2018-06-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_cancelable', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('WORKING', 'Working'), ('CANCELING', 'Canceling'), ('DONE', 'Done'), ('ERROR', 'Error'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=128)),
                ('function_name', models.CharField(max_length=128, verbose_name='job function name')),
                ('args', jsonfield.fields.JSONField(default=[], verbose_name='job function args')),
                ('kwds', jsonfield.fields.JSONField(default={}, verbose_name='job function kwds')),
                ('message', models.TextField(default='')),
                ('payload', jsonfield.fields.JSONField(default={})),
                ('readiness', models.FloatField(default=None, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
